export const works = [
  {
    id: 1,
    img: "/assets/images/work22.png",
    techniques: ["React", "Vite", "react-hot-toast", "@reduxjs/toolkit", "With API"],
    frameworks: ["Tailwind"],
    demo: "https://dashboardfocalx.netlify.app/",
    isResponsive: true,
  },
  {
    id: 2,
    img: "/assets/images/work21.png",
    techniques: [
      "React",
      "Vite",
      "mui/material",
      "node",
      "express js",
      "mongoDB",
    ],
    frameworks: ["bootstrap"],
    demo: "https://github.com/mootaz20/MERN-PROJECT",
    isResponsive: true,
  },
  {
    id: 3,
    img: "/assets/images/work1.png",
    techniques: ["React", "Vite"],
    frameworks: ["Tailwind"],
    demo: "https://mootaz20.github.io/Task-5/",
    isResponsive: true,
  },
  {
    id: 4,
    img: "/assets/images/work3.png",
    techniques: ["React", "swiper", "react-bootstrap"],
    frameworks: ["Bootstrap"],
    demo: "https://mootaz20.github.io/MEDICIO-1/",
    isResponsive: true,
  },
  {
    id: 5,
    img: "/assets/images/work2.png",
    techniques: ["React", "vite"],
    frameworks: ["Pure"],
    demo: "https://mootaz20.github.io/Task-3/",
    isResponsive: true,
  },
  {
    id: 6,
    img: "/assets/images/work13.png",
    techniques: ["React", "vite", "react-bootstrap"],
    frameworks: ["Bootstrap"],
    demo: "https://aigatemootaz.netlify.app/",
    isResponsive: false,
  },
  {
    id: 7,
    img: "/assets/images/work4.png",
    techniques: ["Angular", "ngx-owl-carousel-o"],
    frameworks: ["Bootstrap"],
    demo: "https://mootaz20.github.io/HostClouds/",
    isResponsive: true,
  },
  {
    id: 8,
    img: "/assets/images/work18.png",
    techniques: ["Angular", "Firebase"],
    frameworks: ["bootstrap"],
    demo: "https://mootaz20.github.io/Educationalplatform/",
    isResponsive: false,
  },
  {
    id: 9,
    img: "/assets/images/work19.png",
    techniques: ["Angular", "Firebase"],
    frameworks: ["bootstrap"],
    demo: "https://mootaz20.github.io/Educational-Dashboard/",
    isResponsive: false,
  },
  {
    id: 10,
    img: "/assets/images/work20.png",
    techniques: ["Angular", "Fakestoreapi"],
    frameworks: ["bootstrap"],
    demo: "https://mootaz20.github.io/test/",
    isResponsive: true,
  },
  {
    id: 11,
    img: "/assets/images/work16.png",
    techniques: ["HTML", "CSS", "javaScript"],
    frameworks: ["Pure"],
    demo: "https://mootaz20.github.io/Local-Storage-Example/",
    isResponsive: false,
  },
  {
    id: 12,
    img: "/assets/images/work6.png",
    techniques: ["HTML", "CSS"],
    frameworks: ["Pure"],
    demo: "https://mootaz20.github.io/Grad/",
    isResponsive: false,
  },
  {
    id: 13,
    img: "/assets/images/work7.png",
    techniques: ["HTML", "CSS"],
    frameworks: ["Pure"],
    demo: "https://mootaz20.github.io/Modest/",
    isResponsive: false,
  },
  {
    id: 14,
    img: "/assets/images/work8.png",
    techniques: ["HTML", "CSS", "JavaScript"],
    frameworks: ["Bulma"],
    demo: "https://mootaz20.github.io/Krypton/index.html",
    isResponsive: false,
  },

  {
    id: 15,
    img: "/assets/images/work17.png",
    techniques: ["HTML", "CSS"],
    frameworks: ["Pure"],
    demo: "https://mootaz20.github.io/SEO/",
    isResponsive: false,
  },
  {
    id: 16,
    img: "/assets/images/work15.png",
    techniques: ["HTML", "CSS"],
    frameworks: ["Bulma"],
    demo: "https://mootaz20.github.io/Ninja-Studio/",
    isResponsive: false,
  },
  {
    id: 17,
    img: "/assets/images/work5.png",
    techniques: ["HTML", "CSS"],
    frameworks: ["Pure"],
    demo: "https://mootaz20.github.io/Animation/",
    isResponsive: true,
  },
  {
    id: 18,
    img: "/assets/images/work14.png",
    techniques: ["HTML", "CSS"],
    frameworks: ["Pure"],
    demo: "https://mootaz20.github.io/Background-CSS/",
    isResponsive: false,
  },
];
